name: Plugin CI

on:
  workflow_dispatch:
  push:
    branches:
      - github-actions-test

jobs:
  plugin-ci:
    uses:  outoftheboxplugins/BuildMachines/.github/workflows/compile-plugin.yml@master
    with:
        ue_version: "5.2"
    secrets:
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
